server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

