spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security
    username: mysql
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # or org.hibernate.dialect.MySQLDialect for older versions
    hibernate:
      ddl-auto: none
    show-sql: true
# implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
# implementation 'com.mysql:mysql-connector-j'
#  <dependency>
#   <groupId>com.mysql</groupId>
#   <artifactId>mysql-connector-j</artifactId>
#   <scope>runtime</scope> </dependency>
#  </dependencies>
