spring:
  ai:
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true # auto gen collection
        collection-name: springAi


#	implementation 'org.springframework.ai:spring-ai-advisors-vector-store'
#	implementation 'org.springframework.ai:spring-ai-starter-vector-store-chroma'

